# Generated by Django 4.0.6 on 2022-08-11 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('pirce', models.IntegerField()),
                ('createdat', models.DateField(verbose_name=datetime.datetime(2022, 8, 11, 2, 43, 22, 541100))),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
