# Generated by Django 4.0.6 on 2022-08-11 00:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('oldprice', models.IntegerField(blank=True)),
                ('pirce', models.IntegerField()),
                ('createdat', models.DateField(verbose_name=datetime.datetime(2022, 8, 11, 2, 47, 43, 511941))),
                ('image', models.ImageField(upload_to='photos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
