# Generated by Django 4.0.6 on 2022-08-11 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='createdat',
            field=models.DateField(verbose_name=datetime.datetime(2022, 8, 11, 2, 48, 31, 442931)),
        ),
    ]
