# Generated by Django 4.0.6 on 2022-08-11 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgapp', '0002_remove_product_user_alter_product_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdat',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2022, 8, 11, 2, 50, 26, 4579)),
        ),
    ]
