# Generated by Django 4.0.6 on 2022-08-11 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgapp', '0005_alter_product_options_alter_product_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdat',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 13, 33, 54, 467511)),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.IntegerField(),
        ),
    ]
