# Generated by Django 4.0.6 on 2022-08-11 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgapp', '0006_alter_product_createdat_alter_product_oldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdat',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 14, 10, 10, 387160)),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
