# Generated by Django 4.0.6 on 2022-08-11 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgapp', '0007_alter_product_createdat_alter_product_oldprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('shoes', 'shoes'), ('clothes', 'clothes'), ('Laptops', 'Laptops'), ('bags', 'bags')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='createdat',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 14, 18, 7, 502346)),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mgapp.category'),
        ),
    ]
