# Generated by Django 4.0.6 on 2022-08-12 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgapp', '0016_alter_order_orderdate_alter_orderdetails_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 0, 24, 59, 305612)),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdat',
            field=models.DateField(default=datetime.datetime(2022, 8, 13, 0, 24, 59, 304613)),
        ),
    ]
