# Generated by Django 4.0.6 on 2022-08-13 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgapp', '0017_alter_order_orderdate_alter_product_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 18, 43, 7, 297101)),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdat',
            field=models.DateField(default=datetime.datetime(2022, 8, 13, 18, 43, 7, 297101)),
        ),
    ]
