# Generated by Django 4.0.6 on 2022-08-13 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgapp', '0019_alter_order_orderdate_alter_product_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 20, 11, 25, 691578)),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdat',
            field=models.DateField(default=datetime.datetime(2022, 8, 13, 20, 11, 25, 690578)),
        ),
    ]
