# Generated by Django 4.0.6 on 2022-08-14 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgapp', '0024_remove_payment_zip_alter_order_orderdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 14, 18, 17, 24, 192669), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 18, 17, 24, 192669)),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdat',
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 18, 17, 24, 191668)),
        ),
        migrations.CreateModel(
            name='confirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('Deliverd', 'Deliverd'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled')], default='pending', max_length=100)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgapp.payment')),
            ],
        ),
    ]
