# Generated by Django 4.0.6 on 2022-08-20 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgapp', '0044_alter_info_customer_alter_order_orderdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 23, 54, 21, 686340)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 20, 23, 54, 21, 687339), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdat',
            field=models.DateField(default=datetime.datetime(2022, 8, 20, 23, 54, 21, 685339)),
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
