# Generated by Django 4.1.1 on 2022-09-07 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgapp', '0051_alter_order_orderdate_alter_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 8, 32, 16, 385416)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 7, 8, 32, 16, 386415), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdat',
            field=models.DateField(default=datetime.datetime(2022, 9, 7, 8, 32, 16, 384416)),
        ),
        migrations.AlterField(
            model_name='responseticket',
            name='res',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
